Add report generator and test, move aggregate params
OpenMined/PipelineDP pull request #23
Opened 2021-05-15 16:18 UTC by jspacek

## Description
- This PR introduces the `ReportGenerator` which constructs the explain plan for issue #10.
- It also moves `AggregateParams` and associated classes to a separate file for ease of use. 

## Affected Dependencies
`DPEngine` will be responsible for adding the stages into the report.

## How has this been tested?
- `report_generator_test` uses a stubbed `aggregate` function to print out a report
- Tested with `conda` environment under `Python 3.8`

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2021-05-17 16:17 UTC, dvadym requested changes
Thanks! It looks good. I left some minor comments

2021-05-17 16:17 UTC, dvadym commented on tests/report_generator_test.py
> +    test_report = ("Differential private: Computing metrics: "
I like that text :)

2021-05-17 16:17 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +"""AggregateParameters containing parameters to pass to the DPEngine."""
maybe something like

Contains classes used for specifying DP aggregations parameters.

2021-05-17 16:17 UTC, dvadym commented on pipeline_dp/report_generator.py
> +  """Generate a report based on the metrics and stages in the pipeline.
Nit (i.e. style improvement): Generates

2021-05-17 20:53 UTC, jspacek commented
> Thanks! It looks good. I left some minor comments

@dvadym Thank you for the review! Updated and ready for re-review 🎉

2021-05-18 13:52 UTC, dvadym approved these changes
Thank you!

2021-05-18 13:52 UTC, merged

2021-05-18 16:05 UTC, jspacek commented
Thanks for the merge!