Remove field from AggregateParams
OpenMined/PipelineDP pull request #270
Opened 2022-05-06 11:29 UTC by rialg

## Description
Refactor the class `AggregateParams` by removing the `public_partitions` field, thus making it serializable.

## How has this been tested?

```
$make test
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.9.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /usr/local/google/home/grial/PipelineDP
plugins: timeout-2.1.0
collected 215 items                                                                                                                                                                                                                                          

tests/accumulator_test.py ...................                                                                                                                                                                                                          [  8%]
tests/budget_accounting_test.py ................                                                                                                                                                                                                       [ 16%]
tests/combiners_test.py .................................                                                                                                                                                                                              [ 31%]
tests/dp_computations_test.py ...............                                                                                                                                                                                                          [ 38%]
tests/dp_engine_test.py .........................s....                                                                                                                                                                                                 [ 52%]
tests/pipeline_backend_test.py ...............................................................                                                                                                                                                         [ 81%]
tests/private_beam_test.py .....................                                                                                                                                                                                                       [ 91%]
tests/private_spark_test.py ................                                                                                                                                                                                                           [ 99%]
tests/report_generator_test.py ..                                                                                                                                                                                                                      [100%]

====================================================================================================================== warnings summary ======================================================================================================================
../.local/lib/python3.9/site-packages/hdfs/config.py:15
  /usr/local/google/home/grial/.local/lib/python3.9/site-packages/hdfs/config.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import load_source

../.local/lib/python3.9/site-packages/apache_beam/testing/test_pipeline.py:36
  /usr/local/google/home/grial/.local/lib/python3.9/site-packages/apache_beam/testing/test_pipeline.py:36: PytestCollectionWarning: cannot collect test class 'TestPipeline' because it has a __init__ constructor (from: tests/private_beam_test.py)
    class TestPipeline(Pipeline):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================================================================================== 214 passed, 1 skipped, 2 warnings in 560.84s (0:09:20) ===================================================================================================
```

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2022-05-06 12:21 UTC, dvadym requested changes
Thanks, it looks good! I left a few comments

Could you please also update the following example files:

[examples/quickstart.ipynb](https://github.com/OpenMined/PipelineDP/blob/main/examples/quickstart.ipynb)
[examples/restaurant_visits.ipynb](https://github.com/OpenMined/PipelineDP/blob/main/examples/restaurant_visits.ipynb)
[movie_view_ratings/run_all_frameworks.py](https://github.com/OpenMined/PipelineDP/blob/784961601d26afa0a08beedc7fe15587c3da9987/examples/movie_view_ratings/run_all_frameworks.py#L80)
[codelab/codelab_PipelineDP.ipynb](https://github.com/OpenMined/PipelineDP/blob/main/examples/codelab/codelab_PipelineDP.ipynb)

2022-05-06 12:21 UTC, dvadym commented on pipeline_dp/dp_engine.py
> +    def aggregate(self, col, public_partitions, params: pipeline_dp.AggregateParams,
`public_partitions` is optional argument. Could you please put them to the end of the list and make default value` = None`.

2022-05-06 12:21 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> -    public_partitions: Any = None
This is a part of the public API, it's better to help the user to fix their old code. Could you please deprecate them the same as with `high` 3 lines above.

2022-05-09 10:24 UTC, dvadym commented
Thank you! Changes LGTM! There are some format [errors](https://github.com/OpenMined/PipelineDP/runs/6349890896?check_suite_focus=true)

Could you please run `make format` from source root?

2022-05-09 11:52 UTC, rialg commented
I am going ahead and update: `SumParams`, `VarianceParams`, `MeanParams`, `CountParams` and `PrivacyIdCountParams`

2022-05-09 14:14 UTC, dvadym reviewed
Thank you for removing `public_partitions` in SumParams, MeanParams! Sry I realized that a few minor things missing (see my comments below)

2022-05-09 14:14 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +    public_partitions: Any = None  # deprecated
Could you please add add in __post_init(self) 5 lines below?

```
if self.public_partitions:
  raise ValueError(" AggregateParams.public_partitions is deprecated. Please use public_partitions argument in DPEngine.aggregate insead.")
```

2022-05-09 14:14 UTC, dvadym commented on pipeline_dp/aggregate_params.py
Could you please deprecate (i.e. # deprecate and check in \_\_post_init\_\_)  `public_partitions` in `SumParams`, `CountParams`, `MeanParams`, `VarienceParams` as well?

2022-05-10 08:10 UTC, dvadym approved these changes
Thank you!

2022-05-10 08:10 UTC, merged