Implementing VectorSumCombiner
OpenMined/PipelineDP pull request #276
Opened 2022-05-13 11:56 UTC by rialg

## Description
Following the first described in #264, this PR has the implementation of the `VectorSumCombiner` class, which used to compute vector/array sums.

## Affected Dependencies
Needed to extend [AggregateParams](https://github.com/OpenMined/PipelineDP/blob/3a7b87a5d943ea6b083c45934c8bb1110cbe5766/pipeline_dp/aggregate_params.py#L56) with the fields `norm_kind` and `max_norm`.

## How has this been tested?
* Tests added to `combiners_test.py`
```
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.9.10, pytest-7.1.2, pluggy-1.0.0
plugins: timeout-2.1.0
collected 45 items                                                                                                                                                                                                                                           

tests/combiners_test.py .............................................                                                                                                                                                                                  [100%]

====================================================================================================================== warnings summary ======================================================================================================================
../.local/lib/python3.9/site-packages/hdfs/config.py:15
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import load_source

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================================================================================== 45 passed, 1 warning in 2.20s ================================================================================================================
```

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2022-05-13 15:05 UTC, dvadym commented on pipeline_dp/combiners.py
> +            eps_per_coordinate=self.eps,
eps_per_coordinate = eps/array_size
delta_per_coordinate = delta/array_size

2022-05-16 11:04 UTC, rialg commented on examples/movie_view_ratings/run_all_frameworks.py
> +    if FLAGS.vector_metrics:
@dvadym , I've added a flag to compute vector metrics over the ratings values, which are extracted as vectors with zeros and one in the position of the rating. What other example would be useful to add?

2022-05-16 17:09 UTC, dvadym requested changes
Thank you! It looks good, I left comments

2022-05-16 17:09 UTC, dvadym commented on pipeline_dp/combiners.py
> +        if pipeline_dp.Metrics.SUM in aggregate_params.metrics or \
I thought again, where to check, we should fail eariler, in this case in `[AggregateParams.__post_init()](https://github.com/OpenMined/PipelineDP/blob/3a7b87a5d943ea6b083c45934c8bb1110cbe5766/pipeline_dp/aggregate_params.py#L86)`. Could you please move it there?

2022-05-16 17:09 UTC, dvadym commented on pipeline_dp/combiners.py
> +            raise ValueError("Do not combine scalar with vector metrics")
"Vector sum can not be computed together with scalar metrics, like sum, mean etc"

2022-05-16 17:09 UTC, dvadym commented on pipeline_dp/combiners.py
> +            pipeline_dp.Metrics.COUNT in aggregate_params.metrics or \
Please remove COUNT from this list (count can be computed)

2022-05-16 17:09 UTC, dvadym commented on pipeline_dp/combiners.py
> +from pipeline_dp.aggregate_params import NormKind
According to Google styleguide, it's needed to import modules, not classes. Could you please
1.Add NormKind to [__init__.py](https://github.com/OpenMined/PipelineDP/blob/main/pipeline_dp/__init__.py) (there are public API objects).
2. Use `pipelinedp.NormKind` in the code

2022-05-19 13:28 UTC, dvadym reviewed
Thank you! It looks great. Just a few minor comments

2022-05-19 13:28 UTC, dvadym commented on pipeline_dp/combiners.py
> +            if type(val) is not np.ndarray:
Nit (just learned :) ): More idiomatic way: 
`if not isinstance(val, np.ndarray):`

2022-05-19 13:28 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +    vector_norm_kind: The type of norm to use for the DP calculations.
Nit: VECTOR_SUM metric caluation.

2022-05-19 13:28 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +    vector_max_norm: Bound on each value of a vector.
Please add: Used only for VECTOR_SUM metric.

2022-05-19 13:28 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +    vector_size: Number of coordinates in a vector.
Please add: Used only for VECTOR_SUM metric.

2022-05-20 17:38 UTC, dvadym approved these changes
Thank you!

2022-05-20 17:38 UTC, merged