Expose vector_sum computation to high-level Beam API
OpenMined/PipelineDP pull request #293
Opened 2022-06-13 15:55 UTC by rialg

## Description
This PR continues the work started for #264 . An additional `PrivatePTransform` is added for vector summation in [private_beam.py](https://github.com/OpenMined/PipelineDP/blob/bb4046265e155f45cdd7b4ee91b8d595c1089c72/pipeline_dp/private_beam.py#L96).

## Affected Dependencies
* VectorSumParams class was added to `aggregate_params.py`
* VectorSum class was added to `private_beam.py`

## How has this been tested?
* Tests added to `private_beam_test.py`

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2022-06-14 08:50 UTC, dvadym reviewed
Thanks!

2022-06-14 08:50 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +    min_value: float = None
Nit: remove min_value/max_value (they need only for scalar metrics)

2022-06-14 08:50 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +    vector_norm_kind: NormKind = NormKind.Linf
Please make all vector_* parameters to be non-optional
please remove default NormKind

2022-06-14 08:50 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +        vector_norm_kind: The type of norm. Used only for VECTOR_SUM metric
Nit: remove "Used only for VECTOR_SUM metric" (here and below).

2022-06-15 12:17 UTC, dvadym reviewed
Just a few minor comments

2022-06-15 12:17 UTC, dvadym commented on pipeline_dp/aggregate_params.py
> +    max_partitions_contributed: Optional[int] = None
For now these parameters are not optional for vector sum.

**Explanation**: in aggregate, there are 2 options:
to specify (`max_partitions_contributed` and `max_contributions_per_partition`)
xor to specify `max_contributions`. The 2nd option is not yet supported for VectorSum

After changing, let's keep the same order as it was before (to be consistent with other Params classes). Please ensure that the order is the same in Docstring and in code

2022-06-15 12:17 UTC, dvadym commented on tests/private_beam_test.py
> +            self.assertEqual(params, args[1])
Nit: please check that `public_partitions` is passed to `aggregate`

2022-06-15 12:17 UTC, dvadym commented on tests/private_beam_test.py
> +            col = [(f"{u}", "pk1", [-100.0]) for u in range(30)]
Nit: to use 2 dim vectors as data (to check that it works for multi-dim vectors)

2022-06-29 16:30 UTC, chinmayshah99 requested changes

2022-06-29 16:30 UTC, chinmayshah99 commented on pipeline_dp/aggregate_params.py
> +    budget_weight: float = 1
nit: change this to `1.0`

2024-01-31 18:36 UTC, closed without merging