Fixes OpenMined#297
OpenMined/PipelineDP pull request #299
Opened 2022-06-30 06:51 UTC by parikhanupk

## Description
Fixes OpenMined#297
Add details to the local example file to match its jupyter sibling (https://github.com/OpenMined/PipelineDP/blob/main/examples/restaurant_visits.ipynb) allowing newcomers to read/run either example with similar content - but strictly for a local example dataset.

## Affected Dependencies
None added.
absl-py no longer needed as it's a demo on a fixed local dataset in the example directory itself.

## How has this been tested?
python3 run_without_frameworks.py

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2022-06-30 13:02 UTC, chinmayshah99 requested changes

2022-07-04 06:32 UTC, parikhanupk commented on examples/restaraunt_visits/run_without_frameworks.py
> +This example demonstrates the core functionality of PipelineDP to users who
Just that line or all comments?

2022-07-04 06:52 UTC, chinmayshah99 commented on examples/restaraunt_visits/run_without_frameworks.py
> +This example demonstrates the core functionality of PipelineDP to users who
all comments

2022-07-04 07:28 UTC, parikhanupk commented
Creating a new PR after incorporating the changes as requested.

2022-07-04 07:28 UTC, closed without merging