Add local `keys` operation
OpenMined/PipelineDP pull request #48
Opened 2021-06-21 15:06 UTC by zachferr

## Description
Add local `keys` operation. This closes  #7 
Sorry for the delay here, I went on vacation then I had to catch up on my main work. 

## Affected Dependencies
N/A

## How has this been tested?
- Added a unit test

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2021-06-22 14:53 UTC, lovroprepolec requested changes

2021-06-23 15:09 UTC, zachferr commented on pipeline_dp/pipeline_operations.py
> +            beam.CoGroupByKey() | "Filterding data from public partitions"
The change was accidental I didn't even realize my formatter did it. When you say maintain do you mean change it back to how it was or keep it as is?

2021-06-24 06:30 UTC, lovroprepolec commented on pipeline_dp/pipeline_operations.py
> +            beam.CoGroupByKey() | "Filterding data from public partitions"
No worries. Please change it back. Thank you!

2021-07-01 14:28 UTC, zachferr commented on tests/pipeline_operations_test.py
> +
Done

2021-07-01 14:28 UTC, zachferr commented on pipeline_dp/pipeline_operations.py
> +            beam.CoGroupByKey() | "Filterding data from public partitions"
Fixed the typo and reverted the change.

2021-07-02 09:30 UTC, merged